### ISSUE TITLE
Missing AWS region

### ISSUE THREAD

**Issue by ghost** [YoruNoHikage/apex-api-gateway#3]
For some reason, apex-api-gateway doesn't work when I don't change the code to set a region:

```
mntdeb~/code/talon-smoketest % apex-api-gateway update
config:  ./project.json
Pushing REST API...
{ ConfigError: Missing region in config
    at Request.VALIDATE_REGION (/home/mntmn/.nvm/versions/node/v6.2.0/lib/node_modules/apex-api-gateway/node_modules/aws-sdk/lib/event_listeners.js:81:45)
    at Request.callListeners (/home/mntmn/.nvm/versions/node/v6.2.0/lib/node_modules/apex-api-gateway/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at callNextListener (/home/mntmn/.nvm/versions/node/v6.2.0/lib/node_modules/apex-api-gateway/node_modules/aws-sdk/lib/sequential_executor.js:95:12)
    at /home/mntmn/.nvm/versions/node/v6.2.0/lib/node_modules/apex-api-gateway/node_modules/aws-sdk/lib/event_listeners.js:75:9
    at finish (/home/mntmn/.nvm/versions/node/v6.2.0/lib/node_modules/apex-api-gateway/node_modules/aws-sdk/lib/config.js:307:7)
    at /home/mntmn/.nvm/versions/node/v6.2.0/lib/node_modules/apex-api-gateway/node_modules/aws-sdk/lib/config.js:323:9
    at SharedIniFileCredentials.get (/home/mntmn/.nvm/versions/node/v6.2.0/lib/node_modules/apex-api-gateway/node_modules/aws-sdk/lib/credentials.js:126:7)
    at getAsyncCredentials (/home/mntmn/.nvm/versions/node/v6.2.0/lib/node_modules/apex-api-gateway/node_modules/aws-sdk/lib/config.js:317:24)
    at Config.getCredentials (/home/mntmn/.nvm/versions/node/v6.2.0/lib/node_modules/apex-api-gateway/node_modules/aws-sdk/lib/config.js:337:9)
    at Request.VALIDATE_CREDENTIALS (/home/mntmn/.nvm/versions/node/v6.2.0/lib/node_modules/apex-api-gateway/node_modules/aws-sdk/lib/event_listeners.js:70:26)
```

If I insert this line before new AWS.APIGateway() is called in apex-api-gateway, it works:
`AWS.config.update({region:'eu-west-1'});`

I have the following env vars set up:

```
AWS_REGION=eu-west-1
AWS_DEFAULT_REGION=eu-west-1
```

I also have it in the aws config file:

```
mntdeb~/code/talon-smoketest % cat $HOME/.aws/config 
[default]
region = eu-west-1
```

**Comment by YoruNoHikage** [comment]
Wow, that is weird, it's indeed written in the docs that region is not loaded but it works for me...

**Comment by id0Sch** [comment]
just opened a PR for this
https://github.com/YoruNoHikage/apex-api-gateway/pull/6

**Comment by YoruNoHikage** [comment]
It's been a while, but I can confirm it should work with the env variable or the config file https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/setting-region.html
